### ISSUE TITLE
Treefarm breaks with mods that rename or replace the Surface in Factorio

### ISSUE THREAD

**Issue by Blu3wolf** [Blu3wolf/Treefarm-Lite#16]
Treefarm specifies the surface its entities are placed on - this will break with mods that change the surface used.

**Comment by Blu3wolf** [comment]
Think this should be fixed in develop. Needs testing.

**Comment by StephenWard** [comment]
definitely still broken in 3.7 just search contral.lua for "nauvis"

**Comment by Blu3wolf** [comment]
Darn. That only works is Nauvis is the string for the surface though, and mods can change that.

Sent from my Samsung device

-------- Original message --------
